// packages/solid-js/src/util/index.ts
import { StoreDispatch, StoreResolver } from '@fielder/core';
import { createSignal } from 'solid-js';

export const useSynchronousReducer = <T extends Record<string, any>, A>(
  resolver: StoreResolver<T, A>,
  initial: T
) => {
  const [state, setState] = createSignal(initial);
  const dispatch: StoreDispatch<A, T> = (action) =>
    setState((s) => resolver(s, action, dispatch));
  return [state, dispatch] as const;
};

// packages/react/src/util/index.ts
import {
  useLayoutEffect as useLayoutEffectOriginal,
  useEffect,
  useState,
  useCallback,
  useRef,
} from 'react';

export const useLayoutEffect =
  typeof window !== 'undefined' ? useLayoutEffectOriginal : useEffect;

type StoreDispatch<T, A> = (action: A) => T;
type StoreResolver<T, A> = (
  store: T,
  action: A,
  dispatch: StoreDispatch<T, A>
) => T;

export const useSynchronousReducer = <T, A>(
  resolver: StoreResolver<T, A>,
  initialState: T
) => {
  const stateRef = useRef(initialState);
  const [state, setState] = useState<S>(stateRef.current);

  const dispatch = useCallback<(a: A) => S>((action) => {
    stateRef.current = resolver(stateRef.current, action, dispatch);
    setState(stateRef.current);
    return stateRef.current;
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  return [state, dispatch] as const;
};
